import Head from 'next/head'
import styles from '../styles/Home.module.css'
import firebase from '../firebase/initFirebase'
import WriteToCloudFirestore from '../components/cloudFirestore/Write'
import ReadFromCloudFirestore from '../components/cloudFirestore/Read'

firebase()

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <WriteToCloudFirestore />
        <ReadFromCloudFirestore />
      </main>
    </div>
  )
}
